{"name": "test_integrity_procedure_manufacturer_insert", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.InternalError: Unread result found", "trace": "db_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>\n\n    def test_integrity_procedure_manufacturer_insert(db_connection):\n        with allure.step('Проверка обеспечения целостности данных при добавлении данных через процедуру'):\n            with db_connection as connection:\n>               cursor = connection.cursor()\n\ntest_db.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:704: in cursor\n    self.handle_unread_result(prepared)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>, prepared = None\n\n    def handle_unread_result(self, prepared: bool = False) -> None:\n        \"\"\"Check whether there is an unread result\"\"\"\n        unread_result = self._unread_result if prepared is True else self.unread_result\n        if self.can_consume_results:\n            self.consume_results()\n        elif unread_result:\n>           raise InternalError(\"Unread result found\")\nE           mysql.connector.errors.InternalError: Unread result found\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:961: InternalError"}, "steps": [{"name": "Проверка обеспечения целостности данных при добавлении данных через процедуру", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.InternalError: Unread result found\n", "trace": "  File \"/Users/akopotov/Documents/College/Testing/checkpoint_6_dB_test/test_db.py\", line 64, in test_integrity_procedure_manufacturer_insert\n    cursor = connection.cursor()\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py\", line 704, in cursor\n    self.handle_unread_result(prepared)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py\", line 961, in handle_unread_result\n    raise InternalError(\"Unread result found\")\n"}, "start": 1698417189935, "stop": 1698417189935}], "start": 1698417189935, "stop": 1698417189935, "uuid": "3ecb44e9-5e60-4cab-94bb-b24afcc98df5", "historyId": "aea949440cc6df0b3b90fab2029dc84b", "testCaseId": "aea949440cc6df0b3b90fab2029dc84b", "fullName": "test_db#test_integrity_procedure_manufacturer_insert", "labels": [{"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "45353-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}